### ISSUE TITLE
looking to use this in swift osx desktop app - any ideas?

### ISSUE THREAD

**Issue by johndpope** [rpplusplus/UXKit#3]
<img width="1184" alt="screen shot 2017-05-11 at 2 16 53 pm" src="https://cloud.githubusercontent.com/assets/289994/25964942/8386a438-3654-11e7-9dc0-9d19e0fb7012.png">

**Comment by Dan2552** [comment]
Use a bridging header with
```
#import <UXKit.h>
```

and I also had to remove
```
#import "NSObject-Protocol.h"
```
from `Pods/UXKit/UXKit/Headers/UXKit.h`

**Comment by johndpope** [comment]
cool thanks
